pipeline:
  name: finaldockerpipeline
  identifier: finaldockerpipeline
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: gitHubConnector
        repoName: HarnessReceiptManagement
        build: <+input>
  stages:
    - stage:
        name: BuidPushToACR
        identifier: BuidPushToACR
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
          buildIntelligence:
            enabled: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: <+input>
              namespace: <+input>
              automountServiceAccountToken: true
              nodeSelector: {}
              os: <+input>
          execution:
            steps:
              - step:
                  type: BuildAndPushACR
                  name: BuildAndPushACR
                  identifier: BuildAndPushACR_1
                  spec:
                    connectorRef: <+input>
                    repository: <+input>
                    tags:
                      - <+pipeline.sequenceId>
                    caching: true
                    buildArgs:
                      stage: int
    - stage:
        name: Approval
        identifier: Approval
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: DevStage
                  identifier: DevStage
                  type: HarnessApproval
                  timeout: 8h
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups:
                        - account._account_all_users
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
    - stage:
        name: DeployToAzureAppService
        identifier: DeployToAzureAppService
        description: ""
        type: Deployment
        spec:
          deploymentType: AzureWebApp
          service:
            serviceRef: <+input>
            serviceInputs: <+input>
          environment:
            environmentRef: <+input>
            deployToAll: false
            environmentInputs: <+input>
            serviceOverrideInputs: <+input>
            infrastructureDefinitions: <+input>
          execution:
            steps:
              - step:
                  type: AzureWebAppRollback
                  name: AzureWebAppDeploy
                  identifier: AzureWebAppRollback_1
                  spec: {}
                  timeout: 8h
            rollbackSteps:
              - step:
                  name: WebApp rollback
                  identifier: webAppRollback
                  type: AzureWebAppRollback
                  timeout: 20m
                  spec: {}
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
