pipeline:
  name: harnessreceipt
  identifier: harnessreceipt
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: gitHubConnector
        repoName: HarnessReceiptManagement
        build: <+input>
  stages:
    - stage:
        variables:
          - name: VAR_NAME
            type: String
            description: test
            required: false
            value: latest
        name: build
        identifier: build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
          buildIntelligence:
            enabled: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: test
              namespace: harness-delegate-ng
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: BuildAndPushACR
                  name: BuildAndPushACR_1
                  identifier: BuildAndPushACR_1
                  spec:
                    connectorRef: ACRAZURECONNNECTIVITY
                    repository: tesreg001.azurecr.io/image
                    tags:
                      - $(tag)
                    caching: true
                    buildArgs:
                      stage: int
