pipeline:
  name: harnessreceipt
  identifier: harnessreceipt
  tags: {}
  template:
    templateRef: templateACR
    versionLabel: Version1
    templateInputs:
      properties:
        ci:
          codebase:
            build: <+input>
      stages:
        - stage:
            identifier: deploy
            type: Deployment
            spec:
              service:
                serviceInputs:
                  serviceDefinition:
                    type: AzureWebApp
                    spec:
                      artifacts:
                        primary:
                          primaryArtifactRef: <+input>
                          sources: <+input>
  projectIdentifier: default_project
  orgIdentifier: default
