pipeline:
  name: quicktest
  identifier: quicktest
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: gitHubConnector
        repoName: HarnessReceiptManagement
        build: <+input>
  stages:
    - stage:
        name: buildpush
        identifier: buildpush
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
          buildIntelligence:
            enabled: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: test
              namespace: harness-delegate-ng
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: BuildAndPushACR
                  name: BuildAndPushACR_1
                  identifier: BuildAndPushACR_1
                  spec:
                    connectorRef: ACRAZURECONNNECTIVITY
                    repository: tesreg001.azurecr.io/image
                    tags:
                      - <+pipeline.sequenceId>
                    caching: true
    - stage:
        name: deploy
        identifier: deploy
        description: ""
        type: Deployment
        spec:
          deploymentType: AzureWebApp
          service:
            serviceRef: ACRAZURECONNNECTIVITY
            serviceInputs:
              serviceDefinition:
                type: AzureWebApp
                spec:
                  artifacts:
                    primary:
                      primaryArtifactRef: <+input>
                      sources: <+input>
          environment:
            environmentRef: finalEnv
            deployToAll: false
            infrastructureDefinitions:
              - identifier: quick
          execution:
            steps:
              - step:
                  name: App Service Deployment
                  identifier: App_Service_Deployment
                  type: AzureSlotDeployment
                  timeout: 20m
                  spec:
                    webApp: testwebapp222
                    deploymentSlot: testwebapp222
                    clean: false
            rollbackSteps:
              - step:
                  name: WebApp rollback
                  identifier: webAppRollback
                  type: AzureWebAppRollback
                  timeout: 20m
                  spec: {}
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
